[package]
name = "skygenesisenterprise-aethermail"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/skygenesisenterprise/aether-mail"

[workspace]
members = ["api"]

[workspace.dependencies]
