[package]
name = "skygenesisenterprise-api"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/skygenesisenterprise/api-service"

[workspace]
members = ["api"]

[workspace.dependencies]
