version: "3.8"

# Ce fichier permet de surcharger la configuration Docker pour le développement local
# Il est automatiquement utilisé par docker-compose

services:
  aethermail-dev:
    # Monter des volumes supplémentaires pour le développement
    volumes:
      - .:/app:cached
      - /app/node_modules
      # Monter les configurations locales
      - ./config/local.json:/app/config/local.json
    # Variables d'environnement supplémentaires
    environment:
      - DEBUG=aether-mail:*
      - LOG_LEVEL=debug
    # Ports supplémentaires pour le debugging
    ports:
      - "9229:9229" # Node.js debugger
      - "9222:9222" # Alternative debugger port

  postgres-dev:
    # Persister les données même après docker-compose down
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    # Exposition du port pour les outils externes
    ports:
      - "5433:5432" # Port différent pour éviter les conflits

  redis-dev:
    # Exposition du port pour les outils externes
    ports:
      - "6380:6379" # Port différent pour éviter les conflits
