import type { Workflow, WorkflowTemplate } from "@/lib/api/workflow-types";

export const workflows: Workflow[] = [
  {
    id: "workflow-1",
    name: "Auto Reply to VIP",
    description: "Send automatic replies to VIP customers",
    status: "active",
    trigger: {
      id: "trigger-1",
      type: "email",
      name: "Email",
      description: "When a new email is received",
      config: { filter: "from:vip" },
    },
    actions: [
      {
        id: "action-1",
        type: "auto_reply",
        name: "Auto Reply",
        description: "Send an automatic reply",
        config: { message: "Thank you for your message. We will respond shortly." },
      },
      {
        id: "action-2",
        type: "add_label",
        name: "Add Label",
        description: "Label as VIP",
        config: { label: "VIP" },
      },
    ],
    nodes: [],
    connections: [],
    executionCount: 156,
    successCount: 152,
    failureCount: 4,
    lastExecutedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
  {
    id: "workflow-2",
    name: "Meeting Reminder",
    description: "Create task reminders for calendar events",
    status: "active",
    trigger: {
      id: "trigger-2",
      type: "calendar",
      name: "Calendar",
      description: "When an event starts in 15 minutes",
      config: { minutesBefore: 15 },
    },
    actions: [
      {
        id: "action-3",
        type: "send_notification",
        name: "Send Notification",
        description: "Send reminder",
        config: {},
      },
      {
        id: "action-4",
        type: "create_task",
        name: "Create Task",
        description: "Create follow-up task",
        config: {},
      },
    ],
    nodes: [],
    connections: [],
    executionCount: 89,
    successCount: 89,
    failureCount: 0,
    lastExecutedAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 14).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
  },
  {
    id: "workflow-3",
    name: "Email Forward to Slack",
    description: "Forward important emails to Slack channel",
    status: "inactive",
    trigger: {
      id: "trigger-3",
      type: "email",
      name: "Email",
      description: "When email contains specific keywords",
      config: { filter: "subject:urgent" },
    },
    actions: [
      {
        id: "action-5",
        type: "webhook_call",
        name: "Webhook",
        description: "Call Slack webhook",
        config: { url: "https://hooks.slack.com/..." },
      },
    ],
    nodes: [],
    connections: [],
    executionCount: 23,
    successCount: 21,
    failureCount: 2,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
  },
  {
    id: "workflow-4",
    name: "Daily Digest",
    description: "Send daily summary of unread emails",
    status: "active",
    trigger: {
      id: "trigger-4",
      type: "schedule",
      name: "Schedule",
      description: "Run daily at 8 AM",
      config: { cron: "0 8 * * *" },
    },
    actions: [
      {
        id: "action-6",
        type: "send_email",
        name: "Send Email",
        description: "Send daily digest",
        config: {},
      },
    ],
    nodes: [],
    connections: [],
    executionCount: 30,
    successCount: 28,
    failureCount: 2,
    lastExecutedAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
];

export const templates: WorkflowTemplate[] = [
  {
    id: "template-1",
    name: "Auto Reply",
    description: "Automatically reply to emails",
    category: "Email",
    workflow: {
      name: "Auto Reply",
      status: "draft",
      trigger: {
        id: "trigger-1",
        type: "email",
        name: "Email",
        description: "When a new email is received",
        config: {},
      },
      actions: [
        {
          id: "action-1",
          type: "auto_reply",
          name: "Auto Reply",
          description: "Send an automatic reply",
          config: {},
        },
      ],
      nodes: [],
      connections: [],
    },
  },
  {
    id: "template-2",
    name: "Task Reminder",
    description: "Create reminders from calendar events",
    category: "Productivity",
    workflow: {
      name: "Task Reminder",
      status: "draft",
      trigger: {
        id: "trigger-2",
        type: "calendar",
        name: "Calendar",
        description: "When an event starts",
        config: {},
      },
      actions: [
        {
          id: "action-2",
          type: "create_task",
          name: "Create Task",
          description: "Create a task",
          config: {},
        },
        {
          id: "action-3",
          type: "send_notification",
          name: "Send Notification",
          description: "Send notification",
          config: {},
        },
      ],
      nodes: [],
      connections: [],
    },
  },
];