import type { User, Conversation, Message } from "@/lib/api/meet-types";

export const currentUser: User = {
  id: "user-1",
  name: "John Doe",
  email: "john@company.com",
  avatarUrl: "https://github.com/shadcn.png",
  status: "online",
};

export const users: User[] = [
  { id: "user-2", name: "Sarah Chen", email: "sarah@company.com", status: "online" },
  { id: "user-3", name: "Mike Johnson", email: "mike@company.com", status: "away" },
  { id: "user-4", name: "Emily Davis", email: "emily@company.com", status: "busy" },
  { id: "user-5", name: "Alex Rivera", email: "alex@company.com", status: "offline" },
];

export const conversations: Conversation[] = [
  {
    id: "conv-1",
    type: "direct",
    name: "Sarah Chen",
    participants: [currentUser, users[0]],
    unreadCount: 2,
    isMuted: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    lastMessage: {
      id: "msg-1",
      conversationId: "conv-1",
      senderId: "user-2",
      senderName: "Sarah Chen",
      content: "Hey, did you see the latest updates?",
      timestamp: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    },
  },
  {
    id: "conv-2",
    type: "direct",
    name: "Mike Johnson",
    participants: [currentUser, users[1]],
    unreadCount: 0,
    isMuted: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    lastMessage: {
      id: "msg-2",
      conversationId: "conv-2",
      senderId: "user-1",
      senderName: "You",
      content: "Sure, I'll take a look tomorrow!",
      timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    },
  },
  {
    id: "conv-3",
    type: "channel",
    name: "engineering",
    description: "Engineering team discussions",
    participants: [currentUser, ...users],
    unreadCount: 5,
    isMuted: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    lastMessage: {
      id: "msg-3",
      conversationId: "conv-3",
      senderId: "user-3",
      senderName: "Mike Johnson",
      content: "The deployment is complete!",
      timestamp: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    },
  },
  {
    id: "conv-4",
    type: "channel",
    name: "general",
    description: "General company announcements",
    participants: [currentUser, ...users],
    unreadCount: 0,
    isMuted: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    lastMessage: {
      id: "msg-4",
      conversationId: "conv-4",
      senderId: "user-4",
      senderName: "Emily Davis",
      content: "Welcome to our new team members!",
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    },
  },
  {
    id: "conv-5",
    type: "group",
    name: "Project Alpha",
    participants: [currentUser, users[0], users[1]],
    unreadCount: 1,
    isMuted: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    lastMessage: {
      id: "msg-5",
      conversationId: "conv-5",
      senderId: "user-2",
      senderName: "Sarah Chen",
      content: "Let's schedule a meeting for this",
      timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    },
  },
];

export const messages: Record<string, Message[]> = {
  "conv-1": [
    {
      id: "msg-1-1",
      conversationId: "conv-1",
      senderId: "user-2",
      senderName: "Sarah Chen",
      content: "Hey! How's the project going?",
      timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    },
    {
      id: "msg-1-2",
      conversationId: "conv-1",
      senderId: "user-1",
      senderName: "You",
      content: "Going well! Just finished the main features.",
      timestamp: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    },
    {
      id: "msg-1-3",
      conversationId: "conv-1",
      senderId: "user-2",
      senderName: "Sarah Chen",
      content: "That's great to hear! Can you share the updates?",
      timestamp: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
    },
    {
      id: "msg-1-4",
      conversationId: "conv-1",
      senderId: "user-1",
      senderName: "You",
      content: "Sure, I'll send you the documentation tomorrow morning.",
      timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    },
    {
      id: "msg-1-5",
      conversationId: "conv-1",
      senderId: "user-2",
      senderName: "Sarah Chen",
      content: "Hey, did you see the latest updates?",
      timestamp: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    },
  ],
  "conv-3": [
    {
      id: "msg-3-1",
      conversationId: "conv-3",
      senderId: "user-3",
      senderName: "Mike Johnson",
      content: "Starting the deployment now",
      timestamp: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    },
    {
      id: "msg-3-2",
      conversationId: "conv-3",
      senderId: "user-2",
      senderName: "Sarah Chen",
      content: "Good luck! Let us know when it's done",
      timestamp: new Date(Date.now() - 1000 * 60 * 75).toISOString(),
    },
    {
      id: "msg-3-3",
      conversationId: "conv-3",
      senderId: "user-3",
      senderName: "Mike Johnson",
      content: "The deployment is complete!",
      timestamp: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    },
  ],
};