name: Docker Release

on:
  push:
    tags:
      - 'v*.*.*'  # déclenche le workflow sur les tags de type v1.0.0, v2.1.3, etc.

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ghcr.io/skygenesisenterprise/aether-mail

    steps:
      # 1️⃣ Checkout du repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Log in to GHCR (ou Docker Hub si tu préfères)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3️⃣ Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      # 4️⃣ Build and push Docker image with cache
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${GITHUB_REF#refs/tags/}
          cache-from: type=gha
          cache-to: type=gha,mode=max