name: Docker Release

on:
  push:
    tags:
      - 'v*.*.*'   # déclenche le workflow sur les tags de type v1.0.0, v2.1.3, etc.

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: skygenesisenterprise/aether-mail

    steps:
      # 1️⃣ Checkout du repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Login sur Docker Hub (ou autre registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3️⃣ Build de l'image
      - name: Build Docker image
        run: |
          docker build \
            --build-arg NODE_ENV=production \
            -t $IMAGE_NAME:${GITHUB_REF#refs/tags/} \
            -t $IMAGE_NAME:latest .

      # 4️⃣ Push de l'image
      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:${GITHUB_REF#refs/tags/}
          docker push $IMAGE_NAME:latest
